# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 462)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ipLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ipLineEdit.setGeometry(QtCore.QRect(107, 51, 101, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ipLineEdit.setFont(font)
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.portLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.portLineEdit.setGeometry(QtCore.QRect(260, 50, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.portLineEdit.setFont(font)
        self.portLineEdit.setObjectName("portLineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 50, 41, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 81, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 451, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.connectButton = QtWidgets.QPushButton(self.groupBox)
        self.connectButton.setGeometry(QtCore.QRect(300, 20, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.connectButton.setFont(font)
        self.connectButton.setObjectName("connectButton")
        self.disconnectButton = QtWidgets.QPushButton(self.groupBox)
        self.disconnectButton.setGeometry(QtCore.QRect(380, 20, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.disconnectButton.setFont(font)
        self.disconnectButton.setObjectName("disconnectButton")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(370, 140, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.SendText = QtWidgets.QTextEdit(self.centralwidget)
        self.SendText.setGeometry(QtCore.QRect(90, 130, 250, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.SendText.setFont(font)
        self.SendText.setObjectName("SendText")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 260, 31, 16))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 280, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 300, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 320, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 360, 31, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 340, 31, 16))
        self.label_10.setObjectName("label_10")
        self.baselink = QtWidgets.QLineEdit(self.centralwidget)
        self.baselink.setGeometry(QtCore.QRect(100, 260, 101, 16))
        self.baselink.setObjectName("baselink")
        self.link2 = QtWidgets.QLineEdit(self.centralwidget)
        self.link2.setGeometry(QtCore.QRect(100, 280, 101, 16))
        self.link2.setObjectName("link2")
        self.link3 = QtWidgets.QLineEdit(self.centralwidget)
        self.link3.setGeometry(QtCore.QRect(100, 300, 101, 16))
        self.link3.setObjectName("link3")
        self.link4 = QtWidgets.QLineEdit(self.centralwidget)
        self.link4.setGeometry(QtCore.QRect(100, 320, 101, 16))
        self.link4.setObjectName("link4")
        self.link5 = QtWidgets.QLineEdit(self.centralwidget)
        self.link5.setGeometry(QtCore.QRect(100, 340, 101, 16))
        self.link5.setObjectName("link5")
        self.link6 = QtWidgets.QLineEdit(self.centralwidget)
        self.link6.setGeometry(QtCore.QRect(100, 360, 101, 16))
        self.link6.setObjectName("link6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(210, 260, 31, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(210, 280, 31, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(210, 300, 31, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(210, 320, 31, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(210, 340, 31, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(210, 360, 31, 21))
        self.label_16.setObjectName("label_16")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 230, 231, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 230, 271, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.xline = QtWidgets.QLineEdit(self.groupBox_3)
        self.xline.setGeometry(QtCore.QRect(40, 40, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.xline.setFont(font)
        self.xline.setObjectName("xline")
        self.yline = QtWidgets.QLineEdit(self.groupBox_3)
        self.yline.setGeometry(QtCore.QRect(40, 80, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.yline.setFont(font)
        self.yline.setObjectName("yline")
        self.zline = QtWidgets.QLineEdit(self.groupBox_3)
        self.zline.setGeometry(QtCore.QRect(40, 120, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.zline.setFont(font)
        self.zline.setObjectName("zline")
        self.rzline = QtWidgets.QLineEdit(self.groupBox_3)
        self.rzline.setGeometry(QtCore.QRect(160, 120, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rzline.setFont(font)
        self.rzline.setObjectName("rzline")
        self.ryline = QtWidgets.QLineEdit(self.groupBox_3)
        self.ryline.setGeometry(QtCore.QRect(160, 80, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ryline.setFont(font)
        self.ryline.setObjectName("ryline")
        self.rxline = QtWidgets.QLineEdit(self.groupBox_3)
        self.rxline.setGeometry(QtCore.QRect(160, 40, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rxline.setFont(font)
        self.rxline.setObjectName("rxline")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(20, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(20, 80, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(20, 120, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(140, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(140, 80, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(140, 120, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(110, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(110, 80, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(110, 120, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(230, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(230, 80, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(230, 120, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.PoseButton = QtWidgets.QPushButton(self.centralwidget)
        self.PoseButton.setGeometry(QtCore.QRect(210, 400, 91, 31))
        self.PoseButton.setAutoDefault(False)
        self.PoseButton.setDefault(False)
        self.PoseButton.setFlat(False)
        self.PoseButton.setObjectName("PoseButton")
        self.moveButton = QtWidgets.QPushButton(self.centralwidget)
        self.moveButton.setGeometry(QtCore.QRect(560, 340, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.moveButton.setFont(font)
        self.moveButton.setObjectName("moveButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(570, 240, 67, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.accLine = QtWidgets.QLineEdit(self.centralwidget)
        self.accLine.setGeometry(QtCore.QRect(620, 280, 31, 16))
        self.accLine.setObjectName("accLine")
        self.velLine = QtWidgets.QLineEdit(self.centralwidget)
        self.velLine.setGeometry(QtCore.QRect(620, 310, 31, 16))
        self.velLine.setObjectName("velLine")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(560, 310, 54, 12))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(660, 280, 54, 12))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(660, 310, 54, 12))
        self.label_31.setObjectName("label_31")
        self.ResetButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResetButton.setGeometry(QtCore.QRect(340, 400, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ResetButton.setFont(font)
        self.ResetButton.setObjectName("ResetButton")
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.ipLineEdit.raise_()
        self.portLineEdit.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.sendButton.raise_()
        self.SendText.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.baselink.raise_()
        self.link2.raise_()
        self.link3.raise_()
        self.link4.raise_()
        self.link5.raise_()
        self.link6.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.PoseButton.raise_()
        self.moveButton.raise_()
        self.comboBox.raise_()
        self.accLine.raise_()
        self.velLine.raise_()
        self.label_5.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.ResetButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UR_Client"))
        self.label_2.setText(_translate("MainWindow", "IP地址："))
        self.label_3.setText(_translate("MainWindow", "端口："))
        self.label_4.setText(_translate("MainWindow", "发送："))
        self.groupBox.setTitle(_translate("MainWindow", "网络配置"))
        self.connectButton.setText(_translate("MainWindow", "开始监听"))
        self.disconnectButton.setText(_translate("MainWindow", "断开"))
        self.sendButton.setText(_translate("MainWindow", "发送"))
        self.label.setText(_translate("MainWindow", "机座"))
        self.label_6.setText(_translate("MainWindow", "肩部"))
        self.label_7.setText(_translate("MainWindow", "肘部"))
        self.label_8.setText(_translate("MainWindow", "手腕1"))
        self.label_9.setText(_translate("MainWindow", "手腕3"))
        self.label_10.setText(_translate("MainWindow", "手腕2"))
        self.label_11.setText(_translate("MainWindow", "°"))
        self.label_12.setText(_translate("MainWindow", "°"))
        self.label_13.setText(_translate("MainWindow", "°"))
        self.label_14.setText(_translate("MainWindow", "°"))
        self.label_15.setText(_translate("MainWindow", "°"))
        self.label_16.setText(_translate("MainWindow", "°"))
        self.groupBox_2.setTitle(_translate("MainWindow", "关节位置"))
        self.groupBox_3.setTitle(_translate("MainWindow", "刀具位置"))
        self.label_17.setText(_translate("MainWindow", "X"))
        self.label_18.setText(_translate("MainWindow", "Y"))
        self.label_19.setText(_translate("MainWindow", "Z"))
        self.label_20.setText(_translate("MainWindow", "RX"))
        self.label_21.setText(_translate("MainWindow", "RY"))
        self.label_22.setText(_translate("MainWindow", "RZ"))
        self.label_23.setText(_translate("MainWindow", "mm"))
        self.label_24.setText(_translate("MainWindow", "mm"))
        self.label_25.setText(_translate("MainWindow", "mm"))
        self.label_26.setText(_translate("MainWindow", "rad"))
        self.label_27.setText(_translate("MainWindow", "rad"))
        self.label_28.setText(_translate("MainWindow", "rad"))
        self.PoseButton.setText(_translate("MainWindow", "机器人姿态"))
        self.moveButton.setText(_translate("MainWindow", "移动"))
        self.comboBox.setItemText(0, _translate("MainWindow", "MoveJ"))
        self.comboBox.setItemText(1, _translate("MainWindow", "MoveL"))
        self.label_5.setText(_translate("MainWindow", "关节速度"))
        self.label_29.setText(_translate("MainWindow", "关节加速"))
        self.label_30.setText(_translate("MainWindow", "°/s"))
        self.label_31.setText(_translate("MainWindow", "°/s^2"))
        self.ResetButton.setText(_translate("MainWindow", "Reset"))

